version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    # environment:
    # - TZ=Europe/Madrid  # Set the timezone to Madrid
    # - WEBPASSWORD=yourpassword  # Set a secure password for the web interface
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "/volume1/pihole:/etc/pihole"
      - "/dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
